apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 01-eks-common-apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    # automated: {}
    syncOptions:
      - CreateNamespace=false
  source:
    - repoURL: https://github.com/vettom/ArgoCD.git
      targetRevision: HEAD
      path: .
      helm:
        values: |
          argocd:
            version: 7.8.4
          prometheus_stack:
            enabled: true
            version: 62.3.1
          prometheus_crds:
            version: 14.0.0
          prometheus_blackbox:
            version: 9.3.0
            # targets: []