apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: core
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  sources:
  - repoURL: https://charts.external-secrets.io
    chart: external-secrets
    # targetRevision: 0.8.1
